apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: spark-tekton-demo
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/erikerlandson/spark-tekton-demo.git
